//
//  StyleKit.m
//  Grocery
//
//  Created by James Robert on 9/10/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Cache

static UIColor* _mainColor = nil;
static UIColor* _mainColorLight = nil;
static UIColor* _color = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _mainColor = [UIColor colorWithRed: 1 green: 0.566 blue: 0 alpha: 1];
    _color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _mainColorLight = [StyleKit.color colorWithAlphaComponent: 1];

}

#pragma mark Colors

+ (UIColor*)mainColor { return _mainColor; }
+ (UIColor*)mainColorLight { return _mainColorLight; }
+ (UIColor*)color { return _color; }

#pragma mark Drawing Methods

+ (void)drawCheckboxWithIsChecked: (BOOL)isChecked;
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(2, 2, 13, 13) cornerRadius: 3];
    [StyleKit.mainColor setStroke];
    rectanglePath.lineWidth = 1;
    [rectanglePath stroke];


    if (isChecked)
    {
        //// Rectangle 2 Drawing
        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(5, 5, 7, 7) cornerRadius: 1.75];
        [StyleKit.mainColor setFill];
        [rectangle2Path fill];
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfCheckboxWithIsChecked: (BOOL)isChecked;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(16, 16), NO, 0.0f);
    [StyleKit drawCheckboxWithIsChecked: isChecked];
    UIImage* imageOfCheckbox = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfCheckbox;
}

@end
